[package]
name = "lidoom"
version = "0.0.2"
description = "DOOM port for Project Lighthouse"
edition = "2021"
license = "GPL-2.0"
repository = "https://github.com/fwcd/lidoom"

[dependencies]
doomgeneric = { git = "https://github.com/fwcd/doomgeneric-rs.git", rev = "545a6124a2690f03ac9200abb7b2afd404722696" }
